name: pennypilot
description: A local-first personal finance tracker.
publish_to: 'none'
version: 1.0.0-alpha.0.2

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # Database
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.2

  # UI
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  fl_chart: ^1.1.1
  intl: ^0.20.2

  # Background & Services
  workmanager: ^0.9.0
  
  # Auth & API
  google_sign_in: 6.1.6
  googleapis: ^15.0.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.13

  # Utils
  uuid: ^4.3.3
  logging: ^1.2.0
  json_annotation: ^4.8.1
  dynamic_color: ^1.6.8
  flutter_secure_storage: ^10.0.0
  file_picker: ^10.3.8
  share_plus: ^12.0.1
  path: ^1.8.3
  shared_preferences: ^2.5.4
  url_launcher: ^6.3.2
  window_to_front: ^0.0.3
  googleapis_auth: ^2.0.0
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.9
  isar_generator: ^3.1.0+1
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/pennypilot_logo.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/pennypilot_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/pennypilot_logo.png"
    background_color: "#hex_code"
    theme_color: "#hex_code"
  windows:
    generate: true
    image_path: "assets/pennypilot_logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/pennypilot_logo.png"
