name: pennypilot
description: A local-first personal finance tracker.
publish_to: 'none'
version: 1.0.0-alpha.1.16

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  riverpod_annotation: any
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.1
  google_fonts: ^6.1.0
  intl: ^0.20.2
  workmanager: any
  google_sign_in: ^6.2.4
  googleapis: ^11.4.0
  mediapipe_genai: ^0.0.1
  logging: any
  json_annotation: any
  dynamic_color: any
  flutter_secure_storage: any
  file_picker: ^8.0.0
  share_plus: ^7.2.0
  path: any
  shared_preferences: any
  url_launcher: any
  googleapis_auth: any
  http: ^1.1.0
  cryptography: any
  google_mlkit_text_recognition: any
  image_picker: any
  flutter_colorpicker: any
  lottie: ^2.7.0
  fl_chart: ^1.1.1
  local_auth: any
  csv: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  build_runner: ^2.4.6
  mockito: any
  mocktail: any
  riverpod_generator: any
  isar_generator: ^3.1.0+1
  json_serializable: any
  flutter_launcher_icons: any
  analyzer: ^5.13.0

flutter:
  generate: true
  uses-material-design: true
  # assets:
  #   - assets/pennypilot_logo.png

google_ml_kit:
  text_recognition:
    latin: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/pennypilot_logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/pennypilot_logo.png"
    background_color: "#hex_code"
    theme_color: "#hex_code"
  windows:
    generate: true
    image_path: "assets/pennypilot_logo.png"
    icon_size: 48
