name: pennypilot
description: A local-first personal finance tracker.
publish_to: 'none'
version: 1.0.0-alpha.1.16

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5
  riverpod_annotation: any
  drift: ^2.20.0
  sqlite3_flutter_libs: ^0.5.24
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.1
  google_fonts: ^6.1.0
  intl: ^0.20.2
  workmanager: any
  google_sign_in: ^6.2.4
  googleapis: ^11.4.0
  mediapipe_genai: ^0.0.1
  logging: any
  json_annotation: any
  dynamic_color: any
  flutter_secure_storage: ^9.2.2
  file_picker: ^8.0.0
  share_plus: ^7.2.0
  path: any
  shared_preferences: any
  url_launcher: any
  googleapis_auth: any
  http: ^1.1.0
  cryptography: any
  receipt_recognition: ^0.2.8
  google_mlkit_text_recognition: ^0.14.0
  tflite_flutter: ^0.11.0
  image_picker: any
  flutter_colorpicker: any
  shimmer: ^3.0.0
  lottie: ^3.1.2
  fl_chart: ^1.1.1
  local_auth: ^2.3.0
  csv: ^5.0.3
  go_router: ^14.0.0
  syncfusion_flutter_charts: ^26.1.35
  nearby_connections: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  build_runner: ^2.4.6
  mockito: any
  mocktail: any
  riverpod_generator: any
  isar_generator: ^3.1.0+1
  drift_dev: any
  json_serializable: any
  flutter_launcher_icons: any
  analyzer: any

flutter:
  generate: true
  uses-material-design: true
  # assets:
  #   - assets/pennypilot_logo.png

google_ml_kit:
  text_recognition:
    latin: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/pennypilot logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/pennypilot logo.png"
    background_color: "#121212"
    theme_color: "#121212"
  windows:
    generate: true
    image_path: "assets/pennypilot logo.png"
    icon_size: 48

dependency_overrides:
  intl: ^0.20.2
  analyzer: ^6.4.1
  analyzer_plugin: ^0.11.3
