name: pennypilot
description: A local-first personal finance tracker.
publish_to: 'none'
version: 1.0.0-alpha.1.3

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_riverpod: 
  riverpod_annotation: 

  # Database
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.2

  # UI
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  fl_chart: ^1.1.1
  intl: ^0.20.2

  # Background & Services
  workmanager: ^0.9.0
  
  # Auth & API
  google_sign_in: 
  googleapis: 
  extension_google_sign_in_as_googleapis_auth: 

  # Utils
  uuid: ^4.3.3
  logging: ^1.2.0
  json_annotation: ^4.8.1
  dynamic_color: ^1.6.8
  flutter_secure_storage: ^10.0.0
  file_picker: ^10.3.8
  share_plus: ^12.0.1
  path: ^1.8.3
  shared_preferences: ^2.5.4
  url_launcher: ^6.3.2
  window_to_front: ^0.0.3
  googleapis_auth: ^2.0.0
  http: ^1.2.1
  cryptography: ^2.5.0
  google_mlkit_text_recognition: 
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: 
  mockito: ^5.4.4
  riverpod_generator: 
  isar_generator: ^3.1.0+1
  json_serializable: 
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/pennypilot_logo.png

google_ml_kit:
  text_recognition:
    latin: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/pennypilot_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/pennypilot_logo.png"
    background_color: "#hex_code"
    theme_color: "#hex_code"
  windows:
    generate: true
    image_path: "assets/pennypilot_logo.png"
    icon_size: 48 # min:48, max:256, default: 48
