name: pennypilot
description: A local-first personal finance tracker.
publish_to: 'none'
version: 1.0.0-alpha.1.6

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: any
  riverpod_annotation: any
  isar: any
  isar_flutter_libs: any
  path_provider: any
  cupertino_icons: any
  google_fonts: any
  fl_chart: any
  intl: any
  workmanager: any
  google_sign_in: 6.1.6
  googleapis: ^11.4.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.13
  uuid: any
  logging: any
  json_annotation: any
  dynamic_color: any
  flutter_secure_storage: any
  file_picker: any
  share_plus: any
  path: any
  shared_preferences: any
  url_launcher: any
  window_to_front: any
  googleapis_auth: any
  http: any
  cryptography: any
  google_mlkit_text_recognition: any
  image_picker: any
  flutter_colorpicker: any
  flutter_dotenv: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  build_runner: any
  mockito: any
  mocktail: any
  riverpod_generator: any
  isar_generator: any
  json_serializable: any
  flutter_launcher_icons: any
  analyzer: ^5.13.0

flutter:
  uses-material-design: true
  assets:
    - assets/pennypilot_logo.png

google_ml_kit:
  text_recognition:
    latin: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/pennypilot_logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/pennypilot_logo.png"
    background_color: "#hex_code"
    theme_color: "#hex_code"
  windows:
    generate: true
    image_path: "assets/pennypilot_logo.png"
    icon_size: 48
